### PR TITLE
Fixes #8

### LINKED ISSUE #8: Support for device rotation
Hi, great work on this.

But I have been a little disappointed to see that the notification's frame isn't changed upon device rotation.
Would be a great thing to think about.

### PR DESCRIPTION
**Pull request by enovav**
Adjust the centre of the view when the device is rotated in order to maintain central position in the superview.

### CODE REVIEW

**Comment by gcamp** [comment]
I pushed a fix on master. This is working, but animation is not fluid.

**Comment by enovav** [comment]
Thanks, too bad I didn't turn on slow animations to notice the bad animation.

**Comment by andrewserff** [comment]
The fix only works when you show the notification in portrait mode and then rotate to landscape.  If you view in landscape mode, the notification view shows up towards the left side.  Also, if you show in landscape, then rotate to portrait, the view is in the wrong place again in portrait.

**Comment by enovav** [comment]
This should fix the problem: https://github.com/gcamp/GCDiscreetNotificationView/pull/16

**Comment by gcamp** [comment]
@andrewserff This comment was about my fix or @enovav's fix?

**Comment by enovav** [comment]
@gcamp The bug is with your fix

**Pull request closed without merging**
